dist: trusty

jobs:
  include:
    - stage: Build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t sonarr .
      - docker images
      - docker tag sonarr $DOCKER_USERNAME/sonarr:latest
    - stage: Deploy
      script:
      - docker push $DOCKER_USERNAME/sonarr
