dist: trusty

env:
  jobs:
    - DOCKER_FILE=Dockerfile TAG_PREFIX=
    - DOCKER_FILE=Dockerfile.aarch64 TAG_PREFIX=arm64v8-
    - DOCKER_FILE=Dockerfile.armhf TAG_PREFIX=arm32v7-

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sonarr -f $DOCKER_FILE .
  - docker images
  - docker tag sonarr ${DOCKER_USERNAME}/sonarr:${TAG_PREFIX}latest

stages:
  - test
  - deploy

jobs:
  include:
    - stage: deploy
      name: Deploy
      script:
      - docker push $DOCKER_USERNAME/sonarr
