dist: trusty

env:
- ARCH=
- ARCH=aarch64
- ARCH=armhf

jobs:
  include:
    - stage: Build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t sonarr .
      - docker images
      - docker tag sonarr $DOCKER_USERNAME/sonarr:latest
      - docker push $DOCKER_USERNAME/sonarr