dist: trusty

arch:
  - amd64
  - arm64
os: linux

env:
  global:
    - IMAGE=sonarr
  jobs:
    - DOCKER_FILE=Dockerfile TAG_PREFIX=
    - DOCKER_FILE=Dockerfile.aarch64 TAG_PREFIX=arm64v8-
    - DOCKER_FILE=Dockerfile.armhf TAG_PREFIX=arm32v7-

jobs:
  exclude:
  - arch: amd64
    env: DOCKER_FILE=Dockerfile.aarch64 TAG_PREFIX=arm64v8-
  - arch: amd64
    env: DOCKER_FILE=Dockerfile.armhf TAG_PREFIX=arm32v7-
  - arch: arm64
    env: DOCKER_FILE=Dockerfile TAG_PREFIX=
  include:
    - stage: test
      name: Build
      script:
        - export TAG=${TAG_PREFIX}latest
        - echo Docker tag ${TAG}
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --no-cache --pull -t ${IMAGE}:${TAG} -f $DOCKER_FILE .
        - docker images
        - docker tag ${IMAGE}:${TAG} ${DOCKER_USERNAME}/${IMAGE}:${TAG}
    - name: Deploy
      script: 
        - docker push $DOCKER_USERNAME/${IMAGE}:${TAG}